# Generated by Django 4.2 on 2023-04-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='qaysi vaqtdan')),
                ('to_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='qachongacha')),
                ('kattalar', models.CharField(blank=True, max_length=20, null=True, verbose_name='kattalar soni')),
                ('bolalar', models.CharField(blank=True, max_length=20, null=True, verbose_name='bolalar soni')),
                ('xonalar', models.CharField(blank=True, max_length=20, null=True, verbose_name='xonalar soni')),
                ('checkbox', models.BooleanField(default=False, verbose_name='satus')),
            ],
        ),
    ]
